name: Containerized React Deployment to Gh-Pages

on:
  push:
    branches:
      - master
    paths:
      - client/**
      - .dockerignore
      - .gitignore
      - .github/workflows/react-deployment.yml


jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          docker build --tag conradmugabe/react_docker_ghpages:latest .
